api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: hexastudio_web
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

certificatesResolvers:
  cloudflare:
    acme:
      email: admin@hexastudio.net
      storage: /letsencrypt/acme.json
      caServer: https://acme-v02.api.letsencrypt.org/directory
      dnsChallenge:
        provider: cloudflare
        # CLOUDFLARE_EMAIL and CLOUDFLARE_API_KEY env vars required
  letsencrypt:
    acme:
      email: admin@hexastudio.net
      storage: /letsencrypt/acme.json
      caServer: https://acme-v02.api.letsencrypt.org/directory
      httpChallenge:
        entryPoint: web

log:
  level: INFO

accessLog: {}

metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
